// For types NOT generated by rs-ts

import type { Download } from "./types/Download";
import type { DownloadProgress } from "./types/DownloadProgress";

export type DownloadEntry = {
  url: string;
  download: Download;
  download_progress: DownloadProgress
};